### ISSUE TITLE
overflow issue 

### ISSUE THREAD

**Issue by cderici** [pycket/pycket#253]
The issue happens when we try to read back a zo file with fasl (with compiled pycket). 

```
pypy targetpycket.py --linklets --verbose 1 -c -I racket/kernel/init
Welcome to Pycket v7.1.0.2
> (floating-point-bytes->real (bytes 0 0 0 0 0 0 240 255))
OverflowError: integer 18442240474082181120L is out of bounds
/home/cderici/pycketland/pycket/pypy/rpython/rtyper/lltypesystem/lltype.py(818)typeOf()
 raise OverflowError("integer %r is out of bounds" % (val,))
```

Weirdly, the it doesn't give the error when compiled:

```
p -c -I racket/kernel/init
Welcome to Pycket v7.1.0.2
> (floating-point-bytes->real (bytes 0 0 0 0 0 0 240 255))
-inf 
```

```
r
Welcome to Racket v7.1.0.2.
> (floating-point-bytes->real (bytes 0 0 0 0 0 0 240 255))
-inf.0
```

**Comment by cderici** [comment]
This is a false issue. When we try to load the zo files we're getting a segfault and while I was trying to investigate that with the interpreter I got this overflow error and I mistakenly thought that was the cause of the segfault. As I pointed out in the earlier comment, this function doesn't give an overflow error when run in compiled. 

The bad thing is, we're not gonna be able to use the interpreter for any program that calls this function with these inputs, it seems in particular the `fasl->sexp`.

**Comment by samth** [comment]
I think @cfbolz or someone else from PyPy might be able to help here.

**Comment by samth** [comment]
Reopening since this happens in the interpreter.

**Comment by cderici** [comment]
This isn't about the fasl though, but I couldn't find a way to remove a label from an issue :)

**Comment by samth** [comment]
Here's the simpler reproduction recipe:

```
[samth@huor:~/sw/pycket (fasl) plt] python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpython.rlib.longlong2float
>>> rpython.rlib.longlong2float.longlong2float(18442240474082181120L)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/samth/sw/pycket/pypy/rpython/rlib/longlong2float.py", line 28, in longlong2float
    ll_array[0] = llval
  File "/home/samth/sw/pycket/pypy/rpython/rtyper/lltypesystem/lltype.py", line 1300, in __setitem__
    T2 = typeOf(val)
  File "/home/samth/sw/pycket/pypy/rpython/rtyper/lltypesystem/lltype.py", line 818, in typeOf
    raise OverflowError("integer %r is out of bounds" % (val,))
OverflowError: integer 18442240474082181120L is out of bounds
>>>
```
