### ISSUE TITLE
`typed/rackunit` crashes

### ISSUE THREAD

**Issue by samth** [pycket/pycket#281]
```
Traceback (most recent call last):
  File "/home/samth/sw/pycket/pycket/__main__.py", line 32, in main
    sys.exit(f(sys.argv))
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 46, in entry_point
    return actual_entry(argv)
  File "/home/samth/sw/pycket/pycket/entry_point.py", line 103, in actual_entry
    racket_entry(names, config, pycketconfig, current_cmd_args)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 283, in racket_entry
    namespace_require_plus(require_spec, pycketconfig)
  File "/home/samth/sw/pycket/pycket/racket_entry.py", line 236, in namespace_require_plus
    namespace_require.call_interpret([m], pycketconfig)
  File "/home/samth/sw/pycket/pycket/base.py", line 73, in call_interpret
    return interpret_one(ast, env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2613, in interpret_one
    inner_interpret(ast, env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 2570, in inner_interpret_two_state
    ast, env, cont = ast.interpret(env, cont)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 1099, in interpret
    return w_callable.call_with_extra_info(args_w, env, cont, self)
  File "/home/samth/sw/pycket/pycket/values.py", line 1418, in call_with_extra_info
    return self.code(args, env, cont, extra_call_info)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 270, in remove_extra_info
    return func(*args)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 207, in func_result_handling
    result = func_arg_unwrap(*args)
  File "/home/samth/sw/pycket/pycket/prims/expose.py", line 190, in func_arg_unwrap
    return func(*typed_args)
  File "/home/samth/sw/pycket/pycket/prims/linklet.py", line 735, in instance_set_variable_value
    instance.overwrite_var(name, val)
  File "/home/samth/sw/pycket/pycket/prims/linklet.py", line 103, in overwrite_var
    self.vars[name].set_bang(value)
  File "/home/samth/sw/pycket/pycket/interpreter.py", line 1537, in set_bang
    assert isinstance(self.w_value, values.W_Cell)
AssertionError
> /home/samth/sw/pycket/pycket/interpreter.py(1537)set_bang()
```

```
(Pdb) p self
<pycket.interpreter.LinkletVar object at 0x000055d4a59d9130>
(Pdb) p self.__dict__
{'sym': si.1, 'w_value': <rpython.tool.pairtype.W_StructSize1 object at 0x000055d4a59d9168>, 'is_transparent': False, 'constance': <pycket.values.W_Bool object at 0x000055d414549b78>}
(Pdb) p self.w_value.tostring()
'#<struct-info>'
```

**Comment by samth** [comment]
This is fixed as of aa92b73cc6fdaca3a9c4c397483efd9bbf82ed13
